using CrudBucketMVC.DataAccess;
using CrudBucketMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace CrudBucketMVC.Controllers
{
    public class VideoController : Controller
    {
        private readonly CrudBucketContext _context;
        public VideoController(CrudBucketContext context) 
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var videos = _context.Videos;

            return View(videos);
        }

        [HttpGet]
        [Route("Video/{id:int}")]
        public IActionResult Show(int id)
        {
            var video = _context.Videos.Find(id);

            return View(video);
        }

        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Video video)
        {
            //Take the movie sent in the request and save it to the database
            _context.Videos.Add(video);
            _context.SaveChanges();

            // The id generated by the database is now on the object we added to the context
            var newVideoId = video.Id;

            // Redirect to our route /movies/show and pass in the newMovieId for the id parameter
            return RedirectToAction("show", new { id = newVideoId });
        }

        // GET: /Video/:id/edit
        [Route("/Video/{id:int}/edit")]
        public IActionResult Edit(int id)
        {
            var video = _context.Videos.Find(id);

            return View(video);
        }

        // PUT (via Post): /Movies/:id
        [HttpPost]
        [Route("/Video/{id:int}")]
        public IActionResult Update(Video video)
        {
            _context.Videos.Update(video);
            _context.SaveChanges();

            return RedirectToAction("show", new { id = video.Id });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var video = _context.Videos.Find(id);

            _context.Videos.Remove(video);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}
